version: '3'
services:
  backend:
    build: backend
    expose:
      - "8000"
    links:
      - ganache
    volumes:
      - ./backend:/app

  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
    expose: 
      - "8000"

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"

  nginx:
    # build:
    #   context: ./
    #   dockerfile: nginx/Dockerfile
    image: nginx:latest
    ports:
      - 8000:8000
    links:
      - frontend
      - backend
    volumes:
      - ./nginx:/etc/nginx
      - ./assets:/var/www/blogchain/assets