version: '3'
services:
  db:
    image: postgres:12
    env_file:
      - .envs/.local/.postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - "5432"

  backend: &backend
    build: backend
    expose:
      - "8000"
    env_file:
      - .envs/.local/.backend
    links:
      - ganache
      - db
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: frontend
    volumes:
      - ./frontend:/app
    expose: 
      - "8000"

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"


  redis:
    image: redis:5.0

  celeryworker:
    <<: *backend
    ports: []
    entrypoint: ["./start_celeryworker.sh"]

  celerybeat:
    <<: *backend
    ports: []
    entrypoint: ["./start_celerybeat.sh"]

  flower:
    <<: *backend
    ports:
      - "5555:5555"
    entrypoint: ["./start_flower.sh"]

  nginx:
    image: nginx:latest
    ports:
      - 8000:8000
    links:
      - frontend
      - backend
    volumes:
      - ./nginx:/etc/nginx
      - ./assets:/var/www/blogchain/assets

  truffle:
    build: bc
    links:
      - ganache
    volumes:
      - ./assets:/assets
      - ./bc:/app:ro

volumes:
  pgdata:
