version: '3'
services:
  backend:
    build: backend
    container_name: backend_integration
    env_file:
      - .envs/.local/.backend
    expose:
      - "8000"
    links:
      - db
    volumes:
      - ./backend:/app:ro
    entrypoint: "./tests/start_integration.sh"

  db:
    image: postgres:12
    container_name: db_integration
    env_file:
      - .envs/.local/.postgres
    expose:
      - "5432"

  tavern:
    build:
      dockerfile: tavern/Dockerfile
      context: .
    container_name: tavern_integration
    links:
      - backend
    entrypoint: sleep 365d
    volumes:
      - ./backend:/backend
      - ./tavern:/app
