version: '3'
services:
  backend_test:
    build: backend
    env_file:
      - .envs/.local/.backend
    entrypoint: ["pytest", "--ds=blogchain.settings.test", "--ignore=tests"]

  ganache:
    image: trufflesuite/ganache-cli:latest
    expose:
      - 8545

  truffle_test:
    build:
      context: .
      dockerfile: bc/Dockerfile
    entrypoint: ["truffle", "test"]
    links:
      - ganache
    volumes:
      - ./bc:/app:ro
