version: '3'

services:
  db:
    image: postgres:11.1
    volumes:
      - ./shared/postgresql:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.postgres
    environment:
      # We set PGDATA to a subfolder because Postgres needs this folder to be
      # empty, and we have a .gitkeep file there
      - PGDATA=/var/lib/postgresql/data/pgdata
  app:  &app
    container_name: blogchain-app
    build:
      context: .
      dockerfile: ./docker/local/backend/Dockerfile
    ports:
      - "8081:8000"
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    volumes:
      - ./backend:/app
      - ./shared/media:/app/shared/media
      - ./shared/static:/app/shared/static
      - ./shared/templates:/app/shared/templates
      - ./docs:/docs

  frontend:
    build:
      context: .
      dockerfile: ./docker/local/frontend/Dockerfile
    expose:
      - 8000
    volumes:
      - ./frontend:/app

  nginx:
    build:
      context: .
      dockerfile: ./docker/local/nginx/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - frontend
      - app

  redis:
    image: redis:3.0

  celeryworker:
    <<: *app
    container_name: blogchain-celeryworker
    depends_on:
      - redis
      - db
    ports: []
    command: /start-celeryworker.sh

  celerybeat:
    <<: *app
    container_name: blogchain-celerybeat
    depends_on:
      - redis
      - db
    ports: []
    command: /start-celerybeat.sh

  flower:
    <<: *app
    container_name: blogchain-flower
    ports:
      - "5555:5555"
    command: /start-flower.sh

