version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: docker/local/backend/Dockerfile
    container_name: backend_integration
    command: integration
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
    expose:
      - "8000"
    links:
      - db

  db:
    image: postgres:12
    container_name: db_integration
    expose:
      - "5432"
    env_file:
      - .envs/.local/.postgres

  tavern:
    build:
      dockerfile: docker/local/tavern/Dockerfile
      context: .
    container_name: tavern_integration
    links:
      - backend
