version: '3'
services:
  backend_test:
    build: backend
    env_file:
      - .envs/.local/.backend
    entrypoint: ["pytest", "--ds=blogchain.settings.test", "--ignore=tests"]
    volumes:
     - ./backend:/app

  truffle_test:
    build:
      context: .
      dockerfile: bc/Dockerfile
    entrypoint: ["truffle", "test"]
    volumes:
      - ./bc:/app:ro
