export const AUTH_START_LOGIN = 'AUTH_START_LOGIN';
export const AUTH_START_SIGNUP = 'AUTH_START_SIGNUP';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const FETCH_COMMENTS_FOR_POST = 'FETCH_COMMENTS_FOR_POST';
export const FETCH_COMMENTS_FOR_POST_START = 'FETCH_COMMENTS_FOR_POST_START';
export const FETCH_VOTES_FOR_POST = 'FETCH_VOTES_FOR_POST';
export const FETCH_UPVOTES_FOR_POST = 'FETCH_UPVOTES_FOR_POST';
export const FETCH_UPVOTES_FOR_POST_START = 'FETCH_UPVOTES_FOR_POST_START';
export const FETCH_DOWNVOTES_FOR_POST = 'FETCH_DOWNVOTES_FOR_POST';
export const FETCH_DOWNVOTES_FOR_POST_START = 'FETCH_DOWNVOTES_FOR_POST_START';

export const STORE_POST_START = 'STORE_POST_START';
export const STORE_POST_SERVER_SUCCESS = 'STORE_POST_SERVER_SUCCESS';
export const STORE_POST_SERVER_FAIL = 'STORE_POST_SERVER_FAIL ';
export const STORE_POST_BC_SUCCESS = 'STORE_POST_BC_SUCCESS';
export const STORE_POST_BC_FAIL = 'STORE_POST_BC_FAIL';

export const FETCH_COMMENTS = 'FETCH_COMMENTS';

export const SUBMIT_COMMENT_START = 'SUBMIT_COMMENT_START';
export const SUBMIT_COMMENT_SERVER_SUCCESS = 'SUBMIT_COMMENT_SERVER_SUCCESS';
export const SUBMIT_COMMENT_SERVER_FAIL = 'SUBMIT_COMMENT_SERVER_FAIL';
export const SUBMIT_COMMENT_BC_SUCCESS = 'SUBMIT_COMMENT_BC_SUCCESS';
export const SUBMIT_COMMENT_BC_FAIL = 'SUBMIT_COMMENT_BC_FAIL';

export const FETCH_UPVOTES_FOR_COMMENT = 'FETCH_UPVOTES_FOR_COMMENT';
export const FETCH_DOWNVOTES_FOR_COMMENT = 'FETCH_DOWNVOTES_FOR_COMMENT';

export const SUBMIT_VOTE = {
    START: 'SUBMIT_VOTE_START',
    SERVER_SUCCESS: 'SUBMIT_VOTE_SERVER_SUCCESS',
    SERVER_FAIL: 'SUBMIT_VOTE_SERVER_FAIL',
    BC_SUCCESS: 'SUBMIT_VOTE_BC_SUCCESS',
    BC_FAIL: 'SUBMIT_VOTE_BC_FAIL',
};

export const SUBMIT_POST_VOTE = {
    START: 'SUBMIT_POST_VOTE_START',
    SERVER_SUCCESS: 'SUBMIT_POST_VOTE_SERVER_SUCCESS',
    SERVER_ERROR: 'SUBMIT_POST_VOTE_SERVER_ERROR',
    BC_SUCCESS: 'SUBMIT_POST_VOTE_BC_SUCCESS',
    BC_ERROR: 'SUBMIT_POST_VOTE_BC_ERROR',
};

export const SUBMIT_COMMENT_VOTE = {
    START: 'SUBMIT_COMMENT_VOTE_START',
    SERVER_SUCCESS: 'SUBMIT_COMMENT_VOTE_SERVER_SUCCESS',
    SERVER_ERROR: 'SUBMIT_COMMENT_VOTE_SERVER_ERROR',
    BC_SUCCESS: 'SUBMIT_COMMENT_VOTE_BC_SUCCESS',
    BC_ERROR: 'SUBMIT_COMMENT_VOTE_BC_ERROR',
};

export const INIT_WEB3 = 'INIT_WEB3';
export const INIT_WEB3_SUCCESS = 'INIT_WEB3_SUCCESS';
