export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_COMMENTS_FOR_POST = 'FETCH_COMMENTS_FOR_POST';

export const STORE_POST_START = 'STORE_POST_START';
export const STORE_POST_SERVER_SUCCESS = 'STORE_POST_SERVER_SUCCESS';
export const STORE_POST_SERVER_FAIL = 'STORE_POST_SERVER_FAIL '
export const STORE_POST_BC_SUCCESS = 'STORE_POST_BC_SUCCESS'
export const STORE_POST_BC_FAIL = 'STORE_POST_BC_FAIL'

export const FETCH_COMMENTS = 'FETCH_COMMENTS';

export const SUBMIT_COMMENT_START = 'SUBMIT_COMMENT_START';
export const SUBMIT_COMMENT_SERVER_SUCCESS = 'SUBMIT_COMMENT_SERVER_SUCCESS';
export const SUBMIT_COMMENT_SERVER_FAIL = 'SUBMIT_COMMENT_SERVER_FAIL';
export const SUBMIT_COMMENT_BC_SUCCESS = 'SUBMIT_COMMENT_BC_SUCCESS';
export const SUBMIT_COMMENT_BC_FAIL = 'SUBMIT_COMMENT_BC_FAIL';

export const INIT_WEB3 = 'INIT_WEB3';
