---                                                                   
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  apt: 
    name: "{{ docker_package }}={{ docker_package_version }}"
    state: "{{ docker_package_state }}"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: Add user to docker group
  user: name='{{ item.name }}'
        groups=docker
        append=yes
  with_items: "{{ docker_users }}"

- include_tasks: docker-compose.yml
  when: docker_install_compose

- include: rsyslog.yml

- include: logrotate.yml

