---
- hosts: all
  become: true
  gather_facts: false

  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
    become: true
    tags:
        - always
  - name: Gathering Facts
    setup:
    tags:
        - always

- import_playbook: "playbooks/{{ env }}.yml"

